server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html index;

    # Supporta URL brevi wiki senza prefisso /01-wiki
    location /30-visualizzazioni/ {
        try_files $uri $uri.html $uri/ /01-wiki$uri /01-wiki$uri.html /01-wiki$uri/ =404;
    }

    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    error_page 404 /404.html;
}
